from django.urls import path, include
from . import views, auth_views
from django.contrib.auth import views as auth_views_django

urlpatterns = [
    path('', auth_views.welcome, name='welcome'),
    path('register/', auth_views.register_view, name='register'),
    path('verify-email/<str:username>/', auth_views.verify_email, name='verify_email'),
    path('google-oauth/', auth_views.google_oauth, name='google_oauth'),
    path('login/', auth_views.login_view, name='login'),
    path('logout/', auth_views.logout_view, name='logout'),
    path('forgot-password/', auth_views.forgot_password, name='forgot_password'),
    path('reset-password/', auth_views.reset_password, name='reset_password'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('plagiarism/', views.plagiarism_check, name='plagiarism_check'),
    path('plagiarism-removal/', views.plagiarism_removal, name='plagiarism_removal'),
    path('ai-detection/', views.ai_detection, name='ai_detection'),
    path('text-summarization/', views.text_summarization, name='text_summarization'),
    path('sentiment-analysis/', views.sentiment_analysis, name='sentiment_analysis'),
    path('text-statistics/', views.text_statistics, name='text_statistics'),
    path('text-to-speech/', views.text_to_speech, name='text_to_speech'),
    path('speech-to-text/', views.speech_to_text, name='speech_to_text'),
    path('url-shortener/', views.url_shortener, name='url_shortener'),
    path('delete-url/<str:url_id>/', views.delete_url, name='delete_url'),
    path('qr-generator/', views.qr_generator, name='qr_generator'),
    path('view-qr/<str:qr_id>/', views.view_qr, name='view_qr'),
    path('delete-qr/<str:qr_id>/', views.delete_qr, name='delete_qr'),
    path('add-document/', views.add_document, name='add_document'),
    path('documents/', views.document_list, name='document_list'),
    path('subscription/', views.subscription, name='subscription'),
    path('upgrade/', views.upgrade_subscription, name='upgrade_subscription'),
    path('analytics/', views.analytics, name='analytics'),
    path('about/', auth_views.about_view, name='about'),
    path('contact/', auth_views.contact_view, name='contact'),
    path('blog/', auth_views.blog_view, name='blog'),
    path('careers/', auth_views.careers_view, name='careers'),
    path('privacy/', auth_views.privacy_view, name='privacy_policy'),
    path('terms/', auth_views.terms_view, name='terms_of_service'),
    path('cookies/', auth_views.cookies_view, name='cookie_policy'),
    path('gdpr/', auth_views.gdpr_view, name='gdpr'),
    path('pdf-converter/', views.pdf_converter, name='pdf_converter'),
    path('word-converter/', views.word_converter, name='word_converter'),
    path('excel-converter/', views.excel_converter, name='excel_converter'),
    path('image-converter/', views.image_converter, name='image_converter'),
    path('process-payment/', views.process_payment, name='process_payment'),
    path('checkout/', views.checkout, name='checkout_base'),
    path('checkout/<str:plan>/', views.checkout, name='checkout'),
    path('<str:short_code>/', views.redirect_url, name='redirect_url'),
]
