# Generated by Django 6.0.1 on 2026-01-13 22:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_keywordextraction_languagetranslation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('trial', 'Trial (14 days)'), ('monthly', 'Monthly ($2/month)'), ('yearly', 'Yearly ($20/year)'), ('unlimited', 'Unlimited ($50 one-time)')], default='trial', max_length=20)),
                ('subscription_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
